company/urls.py
from django.urls import path

from company.apps import CompanyConfig
from company.views import DriversListView, DriverCreateView, DriverUpdateView, DriverDeleteView, VehicleListView, \
    VehicleCreateView, VehicleDeleteView, VehicleUpdateView

app_name = CompanyConfig.name

urlpatterns = [
    path('drivers/', DriversListView.as_view(), name='drivers_list'),
    path('driver_create/', DriverCreateView.as_view(), name='driver_create'),
    path('driver_update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('driver_delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),
    path('vehicles/', VehicleListView.as_view(), name='vehicles_list'),
    path('vehicle_create/', VehicleCreateView.as_view(), name='vehicle_create'),
    path('vehicle_update/<int:pk>/', VehicleUpdateView.as_view(), name='vehicle_update'),
    path('vehicle_delete/<int:pk>/', VehicleDeleteView.as_view(), name='vehicle_delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logistics.urls', namespace='logistics')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('user_profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    ]

company/models.py
from django.db import models


class Driver(models.Model):
    """ Модель объекта водитель """

    driver_name = models.CharField(max_length=255, verbose_name='Имя водителя')

    def __str__(self):
        return self.driver_name

    class Meta:
        verbose_name = 'Водитель'
        verbose_name_plural = 'Водители'


class Vehicle(models.Model):
    """ Модель объекта транспортное средство """

    vehicle_brand = models.CharField(max_length=255, verbose_name='Марка авто')
    vehicle_registration = models.CharField(max_length=255, verbose_name='Регистрационный номер')
    need_inspection = models.BooleanField(default=False, verbose_name='Необходимость осмотра')
    need_technical_inspection = models.BooleanField(default=False, verbose_name='Необходимость ТО')
    is_overloading = models.BooleanField(default=False, verbose_name='Перегруз')
    is_overheating = models.BooleanField(default=False, verbose_name='Перегрев')

    def __str__(self):
        return self.vehicle_registration

    class Meta:
        verbose_name = 'Транспортное средство'
        verbose_name_plural = 'Транспортные средства'

company/forms.py
from django import forms

from company.models import Driver, Vehicle


class DriverForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(DriverForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Driver
        fields = '__all__'


class VehicleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(VehicleForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Vehicle
        fields = '__all__'

company/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from company.forms import DriverForm, VehicleForm
from company.models import Driver, Vehicle


class DriversListView(ListView):
    """ Список объектов водители """

    model = Driver

    template_name = 'company/drivers_list.html'

    def get_context_data(self, **kwargs):
        """ Определяем контекстную информацию """

        context = super().get_context_data(**kwargs)

        drivers = Driver.objects.all()  # получаем всех водителей

        context['title'] = 'Водители'
        context['drivers'] = drivers

        return context


class DriverCreateView(CreateView):
    """ Создание объекта водитель """

    model = Driver

    form_class = DriverForm
    template_name = 'company/driver_form.html'

    def form_valid(self, form):
        """ Проверка и сохранение данных """

        self.object = form.save(commit=False)
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Определяем контекстную информацию """

        context = super().get_context_data(**kwargs)

        context['title'] = 'Добавление водителя'

        return context

    def get_success_url(self):
        return reverse('company:drivers_list')


class DriverUpdateView(UpdateView):
    """ Изменение объекта водитель """

    model = Driver

    form_class = DriverForm
    success_url = reverse_lazy('company:drivers_list')

    def form_valid(self, form):
        """ Проверка и сохранение данных """

        if form.is_valid():
            new_driver = form.save()
            new_driver.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Определяем контекстную информацию """

        context = super().get_context_data(**kwargs)

        context['title'] = 'Изменения водителя'

        return context


class DriverDeleteView(DeleteView):
    """ Удаление объекта водитель """

    model = Driver
    success_url = reverse_lazy('company:drivers_list')


class VehicleListView(ListView):
    """ Список объектов транспортные средства """

    model = Vehicle

    template_name = 'company/vehicles_list.html'

    def get_context_data(self, **kwargs):
        """ Контекстная информация """

        context = super().get_context_data(**kwargs)

        vehicles = Vehicle.objects.all()  # получаем всех транспортных средств

        context['title'] = 'Транспортные средства'
        context['vehicles'] = vehicles

        return context


class VehicleCreateView(CreateView):
    """ Создание объекта транспортное средство """

    model = Vehicle

    form_class = VehicleForm
    template_name = 'company/vehicle_form.html'

    def form_valid(self, form):
        """ Проверка и сохранение данных """

        self.object = form.save(commit=False)
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Контекстная информация """

        context = super().get_context_data(**kwargs)

        context['title'] = 'Добавление транспортного средства'

        return context

    def get_success_url(self):
        return reverse('company:vehicles_list')


class VehicleUpdateView(UpdateView):
    """ Изменение объекта транспортное средство """

    model = Vehicle

    form_class = VehicleForm
    success_url = reverse_lazy('company:vehicles_list')

    def form_valid(self, form):
        """ Проверка и сохранение данных """

        if form.is_valid():
            new_vehicle = form.save()
            new_vehicle.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Контекстная информация """

        context = super().get_context_data(**kwargs)

        context['title'] = 'Изменение транспортного средства'

        return context


class VehicleDeleteView(DeleteView):
    """ Удаление объекта транспортное средство """

    model = Vehicle
    success_url = reverse_lazy('company:vehicles_list')

company/templates/company/driver_confirm_delete.html
{% extends "logistics/base.html" %}

{% block content %}

<title>{{ title }}</title>

    <div class="col-lg-4 col-md-8">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h4 class="card-title">Хотите удалить водителя: </h4>
                            <p>{{driver.driver_name}} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'company:drivers_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<br>
{% endblock %}

company/templates/company/driver_form.html
{% extends 'logistics/base.html' %}

{% block content%}

<title>{{ title }}</title>

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if driver %}
                        <h3 class="card-title">Форма для изменения водителя</h3>
                        {% else %}
                        <h3 class="card-title">Форма для добавления водителя</h3>
                        {% endif %}
                        <p></p>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
</div>
<br>
{% endblock %}

company/templates/company/drivers_list.html
{% extends 'logistics/base.html' %}

{% block content%}

<title>{{ title }}</title>

<div class="container">

    <div class="row">
        <div class="col-12">
            <h3>Список водителей</h3>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th scope="col">Водитель</th>
                    <th scope="col">Действия</th>
                </tr>
                </thead>
                <tbody>
                {% for driver in drivers %}
                <tr>
                    <td>{{ driver.driver_name }}</td>
                    <td>
                        <a href="{% url 'company:driver_update' driver.pk %}"
                           class="btn btn-sm btn-outline-warning">Редактировать</a>
                        <a href="{% url 'company:driver_delete' driver.pk %}"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <a href="{% url 'company:driver_create' %}" class="btn btn-sm btn-outline-success">
            Добавить водителя</a>
    </div>
</div>
<br>
{% endblock %}

company/templates/company/vehicle_confirm_delete.html
{% extends "logistics/base.html" %}

{% block content %}

<title>{{ title }}</title>

    <div class="col-lg-4 col-md-8">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h4 class="card-title">Хотите удалить транспортное средство: </h4>
                            <p>{{vehicle.vehicle_brand}} {{vehicle.vehicle_registration}} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'company:vehicles_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<br>
{% endblock %}

company/templates/company/vehicle_form.html
{% extends 'logistics/base.html' %}

{% block content%}

<title>{{ title }}</title>

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if vehicle %}
                        <h3 class="card-title">Форма для изменения транспортного средства</h3>
                        {% else %}
                        <h3 class="card-title">Форма для добавления транспортного средства</h3>
                        {% endif %}
                        <p></p>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
</div>
<br>
{% endblock %}

company/templates/company/vehicles_list.html
{% extends 'logistics/base.html' %}

{% block content%}

<title>{{ title }}</title>

<div class="container">

    <div class="row">
        <div class="col-12">
            <h3>Список транспортных средств</h3>
            <table class="table table-condensed table-bordered table-striped">
                <thead>
                <tr>
                    <th>Транспортное средство</th>
                    <th>Регистрационный номер</th>
                    <th>Необходимость осмотра</th>
                    <th>Необходимость ТО</th>
                    <th>Перегруз</th>
                    <th>Перегрев</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                {% for vehicle in vehicles %}
                <tr>
                    <td>{{ vehicle.vehicle_brand }}</td>
                    <td>{{ vehicle.vehicle_registration }}</td>

                    {% if vehicle.need_inspection %}
                    <td>Да</td>
                    {% else %}
                    <td>Нет</td>
                    {% endif %}

                    {% if vehicle.need_technical_inspection %}
                    <td>Да</td>
                    {% else %}
                    <td>Нет</td>
                    {% endif %}

                    {% if vehicle.is_overloading %}
                    <td>Да</td>
                    {% else %}
                    <td>Нет</td>
                    {% endif %}

                    {% if vehicle.is_overheating %}
                    <td>Да</td>
                    {% else %}
                    <td>Нет</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'company:vehicle_update' vehicle.pk %}"
                           class="btn btn-condensed btn-sm btn-outline-warning">Редактировать</a>
                        <a href="{% url 'company:vehicle_delete' vehicle.pk %}"
                           class="btn btn-condensed btn-sm btn-outline-danger">Удалить</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <a href="{% url 'company:vehicle_create' %}" class="btn btn-sm btn-outline-success">
            Добавить транспортное средство</a>
    </div>
</div>
<br>
<style>
    /* Стили для шрифта таблицы */
.table-condensed{
  font-size: 12px;
}

/* Стили для шрифта кнопок в таблице */
.btn-condensed{
  font-size: 12px;
}
</style>
{% endblock %}