config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logistics.urls', namespace='logistics')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('user_profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """ Модель пользователя """

    username = None

    user_email = models.EmailField(verbose_name='Почта', unique=True)
    user_phone = models.CharField(max_length=20, verbose_name='Телефон', null=True, blank=True)
    is_staff = models.BooleanField(default=False, verbose_name='Сотрудник')

    USERNAME_FIELD = 'user_email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms

from users.models import User


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ["user_email", "user_phone", 'first_name', "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()
        return user


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ["user_email", 'first_name', 'last_name', "user_phone",]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


# class UserUpdateForm(StyleFormMixin, UserChangeForm):
#     class Meta:
#         model = User
#         fields = ['user_business_area',]
#
#     def __init__(self, business_id, *args, **kwargs):
#         super(UserUpdateForm, self).__init__(*args, **kwargs)
#
#         business = Business.objects.get(id=business_id)
#
#         self.fields['user_business_area'].queryset = BusinessArea.objects.filter(business=business)
#
#         self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView

from users.forms import UserLoginForm, UserRegisterForm, UserForm
from users.models import User


class UserLoginView(LoginView):
    """ Авторизация пользователя """

    model = User

    template_name = 'users/login.html'

    form_class = UserLoginForm


class UserRegisterView(CreateView):
    """ Регистрация пользователя """

    model = User

    form_class = UserRegisterForm

    template_name = 'users/register.html'

    success_url = reverse_lazy('users:login')


class UserProfileView(UpdateView):
    """ Изменение профиля пользователя """

    model = User

    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('users:user_detail', kwargs={'pk': self.kwargs['pk']})


class UserDetailView(DetailView):
    """ Информация о пользователе """

    model = User

    def get_object(self, queryset=None):
        return self.request.user


# class UserUpdateView(UpdateView):
#     """ Обновление объекта сферы деятельности пользователя """
#
#     model = User
#     form_class = UserUpdateForm
#
#     def get_object(self, queryset=None):
#
#         return self.request.user
#
#     def get_form_kwargs(self):
#         kwargs = super().get_form_kwargs()
#
#         kwargs['business_id'] = self.kwargs.get('business_id')
#
#         return kwargs
#
#     def get_success_url(self):
#         return reverse('users:user_detail', kwargs={'pk': self.request.user.id})

users/templates/users/login.html
{% extends 'logistics/base.html' %}

{% block content%}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>

                </div>
            </div>
        </div>

    </form>
    <br>
    <a href="#">Забыли Ваш пароль?</a>
</div>
<br>
{% endblock %}

users/templates/users/register.html
{% extends 'logistics/base.html' %}

{% block content%}

        <div class="col-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h4 class="card-title">
                            Регистрация
                        </h4>
                    </div>
                </div>
                <div id="user_form">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
                </div>
            </div>
        </div>

    </form>
        </div>

<style>
    /* Стили для карточки регистрации */
    #user_form {
      font-size: 12px;
    }

</style>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'logistics/base.html' %}
{% block content%}

<div class="container" style="border:1px solid #cecece; border-radius: 4px; background-color:#b2dfdb;">

    {% if is_owner %}
    <div class="row mt-4 mb-4">

    </div>
    {% endif %}

    <!-- Правая часть с информацией о юзере -->
    <div class="col-md-9">
        <br>
        <p><b>Имя:</b> {{user.first_name}} </p>
        <p><b>Имя:</b> {{user.last_name}} </p>
        <p><b>Электронная почта:</b> {{user.user_email}} </p>
        <p><b>Телефон для связи:</b> {{user.user_phone}}</p>

    </div>

</div>
<br>
<div>
    <a class="btn btn-outline-dark me-2" href="{% url 'users:user_profile' user.pk %}">Редактировать</a>
</div>
<br>


{% endblock %}

users/templates/users/user_form.html
{% extends 'logistics/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h6>Профиль пользователя</h6>
            </div>
            <div id="user_form">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-info">Сохранить</button>
                </form>
            </div>


            </div>
        </div>
    </div>
</div>
<br>

<style>
    /* Стили для ввода номера заявки */
    #user_form {

      font-size: 12px;
    }

</style>
{% endblock %}