company/urls.py
from django.urls import path

from company.apps import CompanyConfig
from company.views import DriversListView, DriverCreateView, DriverUpdateView, DriverDeleteView, VehicleListView, \
    VehicleCreateView, VehicleDeleteView, VehicleUpdateView

app_name = CompanyConfig.name

urlpatterns = [
    path('drivers/', DriversListView.as_view(), name='drivers_list'),
    path('driver_create/', DriverCreateView.as_view(), name='driver_create'),
    path('driver_update/<int:pk>/', DriverUpdateView.as_view(), name='driver_update'),
    path('driver_delete/<int:pk>/', DriverDeleteView.as_view(), name='driver_delete'),
    path('vehicles/', VehicleListView.as_view(), name='vehicles_list'),
    path('vehicle_create/', VehicleCreateView.as_view(), name='vehicle_create'),
    path('vehicle_update/<int:pk>/', VehicleUpdateView.as_view(), name='vehicle_update'),
    path('vehicle_delete/<int:pk>/', VehicleDeleteView.as_view(), name='vehicle_delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logistics.urls', namespace='logistics')),
    path('users/', include('users.urls', namespace='users')),
    path('company/', include('company.urls', namespace='company')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

logistics/urls.py
from django.urls import path

from logistics.apps import LogisticsConfig
from logistics.views import HomePageView, ItineraryListView, ItineraryCreateView, ItineraryPlanListView, \
    ItineraryUpdateView, ItineraryDeleteView

app_name = LogisticsConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('itineraries/', ItineraryListView.as_view(), name='itineraries_list'),  # список разгрузок
    path('itinerary_create/', ItineraryCreateView.as_view(), name='itinerary_create'),
    path('itinerary_update/<int:pk>/', ItineraryUpdateView.as_view(), name='itinerary_update'),
    path('itinerary_delete/<int:pk>/', ItineraryDeleteView.as_view(), name='itinerary_delete'),
    path('planing_itineraries/', ItineraryPlanListView.as_view(), name='itineraries_plan_list'),
    ]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path


from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('user_profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    ]

logistics/models.py
from django.db import models

from company.models import Vehicle, Driver
from config import settings


class Itinerary(models.Model):
    """ Модель объекта маршрут """

    itinerary_number = models.CharField(max_length=10, verbose_name='Номер маршрута')
    itinerary_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата составления')
    itinerary_date_start = models.DateTimeField(verbose_name='Дата погрузки')
    itinerary_date_finish = models.DateTimeField(verbose_name='Дата разгрузки')
    itinerary_point_from = models.CharField(max_length=100, verbose_name='Место погрузки')
    itinerary_point_to = models.CharField(max_length=100, verbose_name='Место разгрузки')
    itinerary_vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, verbose_name='Транспортное средство')
    itinerary_driver = models.ForeignKey(Driver, on_delete=models.CASCADE, verbose_name='Водитель')
    itinerary_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                        verbose_name='Менеджер')

    def __str__(self):
        return f"{self.itinerary_date_finish} в {self.itinerary_point_to}"

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'

logistics/forms.py
from django import forms

from company.models import Vehicle, Driver
from logistics.models import Itinerary


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ItineraryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):

        super(ItineraryForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Itinerary
        # fields = '__all__'
        exclude = ('itinerary_owner',)

        # widgets = {
        #     'itinerary_date_start': forms.DateTimeInput(
        #         attrs={'type': 'datetime-local'}
        #     ),
        #     'itinerary_date_finish': forms.DateTimeInput(
        #         attrs={'type': 'datetime-local'}),
        #     'itinerary_vehicle': forms.Select()
        # }

logistics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DeleteView

from company.models import Vehicle, Driver
from logistics.forms import ItineraryForm
from logistics.models import Itinerary
from logistics.services import get_plan_days
from users.models import User


class HomePageView(TemplateView):
    """ Главная страница """

    template_name = 'logistics/home.html'

    def get_context_data(self, **kwargs):
        """ Определяем контекстную информацию """

        context = super().get_context_data(**kwargs)

        context['title'] = 'Транспортная логистика'

        return context


class ItineraryListView(ListView):
    """ Список объектов маршруты """

    model = Itinerary

    template_name = 'logistics/itineraries_list.html'

    def get_context_data(self, **kwargs):
        """ Контекстная информация """

        context = super().get_context_data(**kwargs)

        itineraries = Itinerary.objects.all()  # получаем все маршруты

        context['title'] = 'Маршруты'
        context['itineraries'] = itineraries

        return context


class ItineraryCreateView(CreateView):
    """ Создание объекта маршрут """

    model = Itinerary

    # form_class = ItineraryForm
    fields = ['itinerary_number',
              'itinerary_date_start',
              'itinerary_date_finish',
              'itinerary_point_from',
              'itinerary_point_to',
              'itinerary_vehicle',
              'itinerary_driver']

    template_name = 'logistics/itinerary_form.html'

    def form_valid(self, form):
        """ Проверка и сохранение данных """

        self.object = form.save(commit=False)

        # присваиваем значение создателя маршрута текущего пользователя
        self.object.itinerary_owner = self.request.user

        self.object.save()
        print("Ok")

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Контекстная информация """

        context = super().get_context_data(**kwargs)

        vehicles = Vehicle.objects.all()  # получаем всех транспортных средств
        drivers = Driver.objects.all()  # получаем всех водителей

        context['title'] = 'Создание маршрута'
        context['vehicles'] = vehicles
        context['drivers'] = drivers

        return context

    def get_success_url(self):
        return reverse('logistics:itineraries_list')


# def itinerary_create(request):
#     """ Создание объекта маршрут """
#
#     if request.method == 'POST':
#
#         form = ItineraryForm(request.POST)
#
#         if form.is_valid():
#             new_itinerary = Itinerary()
#             save_itinerary(
#                 request=request,
#                 new_itinerary=new_itinerary,
#                 itinerary_form=form,
#             )
#
#         vehicles = Vehicle.objects.all()  # получаем всех транспортных средств
#         drivers = Driver.objects.all()  # получаем всех водителей
#
#         context = {
#             'title': 'Создание маршрута',
#             'vehicles': vehicles,
#             'drivers': drivers,
#         }
#
#         return render(request, 'logistics/itineraries_list', {'context': context})
#
#     else:
#         form = ItineraryForm()
#
#     return render(request, 'logistics/itinerary_form.html', {'form': form})


class ItineraryUpdateView(generic.edit.UpdateView):
    """ Изменение объекта маршрут """

    model = Itinerary

    form_class = ItineraryForm

    # fields = ['itinerary_number',
    #           'itinerary_date_start',
    #           'itinerary_date_finish',
    #           'itinerary_point_from',
    #           'itinerary_point_to',
    #           'itinerary_vehicle',
    #           'itinerary_driver']

    template_name = 'logistics/itinerary_update.html'

    success_url = reverse_lazy('logistics:itineraries_list')

    def get_object(self, queryset=None):
        itinerary = super(ItineraryUpdateView, self).get_object()

        return itinerary

    def form_valid(self, form):
        """ Проверка и сохранение данных """

        if form.is_valid():
            new_itinerary = form.save()
            new_itinerary.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """ Определяем контекстную информацию """

        context = super().get_context_data(**kwargs)

        vehicles = Vehicle.objects.all()  # получаем всех транспортных средств
        drivers = Driver.objects.all()  # получаем всех водителей

        context['title'] = 'Изменение маршрута'
        context['vehicles'] = vehicles
        context['drivers'] = drivers
        # context['itinerary_number'] = self.object.itinerary_number

        return context


class ItineraryDeleteView(DeleteView):
    """ Удаление объекта маршрут """

    model = Itinerary
    success_url = reverse_lazy('logistics:itineraries_list')


class ItineraryPlanListView(ListView):
    """ Список запланированных разгрузок """

    model = Itinerary

    template_name = 'logistics/itineraries_plan_list.html'

    def get_context_data(self, **kwargs):
        """ Контекстная информация """

        context = super().get_context_data(**kwargs)

        itineraries = Itinerary.objects.all()  # получаем все маршруты
        users = User.objects.all()  # получаем всех пользователей

        days = get_plan_days()  # получаем список дат планируемых разгрузок

        context['title'] = 'Маршруты'
        context['itineraries'] = itineraries
        context['users'] = users
        context['days'] = days

        return context

logistics/templates/logistics/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Display:700,900" rel="stylesheet">
    <link href="/static/css/blog.css" rel="stylesheet">
</head>

<body class="d-flex flex-column min-vh-100">

<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <img src="/media/logistics/aHlitnkGam8.jpg" width="110" height="100">


            </div>
            <div class="col-4 text-center">
                <h1>Транспортная логистика</h1>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="mx-3">
                        <circle cx="10.5" cy="10.5" r="7.5"></circle>
                        <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                    </svg>
                </a>
                <nav class="nav d-flex justify-content-between">
                    {% if user.is_authenticated %}
                    <div class="header">
                        <a class="btn btn-outline-dark me-2" href="{% url 'users:user_detail' user.pk %}">Профиль</a>
                        <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-dark me-2">Выйти</button>
                        </form>
                    </div>
                    {% else %}
                    <div class="header">
                        <a class="btn btn-outline-dark me-2" href="{% url 'users:login' %}">Войти</a>
                        <a class="btn btn-outline-dark me-2" href="{% url 'users:register' %}">Регистрация</a>
                    </div>
                    {% endif %}
                </nav>
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="{% url 'logistics:home' %}">ГЛАВНАЯ</a>
            <a class="p-2 text-muted" href="{% url 'company:drivers_list' %}">ВОДИТЕЛИ</a>
            <a class="p-2 text-muted" href="{% url 'company:vehicles_list' %}">АВТОМОБИЛИ</a>
            <a class="p-2 text-muted" href="{% url 'logistics:itineraries_list' %}">МАРШРУТНЫЕ ЛИСТЫ</a>
            <a class="p-2 text-muted" href="#">КОНТАКТЫ </a>

        </nav>
    </div>
    <hr class="hr" />

    {% block content %}
    {% endblock %}


</div>



<footer class="text-muted flex-shrink-0 mt-auto">
    <div class="container">
        <p class="float-right">
            <a href="#"></a>
        </p>
        <p>Cargo Web &copy; {% now 'Y' %}</p>

    </div>
</footer>

<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/holder.min.js"></script>
<script>
    Holder.addTheme('thumb', {
      bg: '#55595c',
      fg: '#eceeef',
      text: 'Thumbnail'
    });
</script>
</body>
</html>

logistics/templates/logistics/city_confirm_delete.html
{% extends "logistics/base.html" %}

{% block content %}

    <div class="col-lg-4 col-md-8">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h4 class="card-title">Хотите удалить город: </h4>
                            <p>{{city.city_name}} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'logistics:cities_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<br>
{% endblock %}

logistics/templates/logistics/home.html
{% extends 'logistics/base.html' %}
{% load static %}

{% block content %}

<title>{{ title }}</title>

<div class="jumbotron p-3 p-md-3 text-white text-center rounded bg-warning">
    <div class="col-md-12 px-0">
        <h1 class="display-4">Транспортная компания О2</h1>
        <p class="lead my-3">Весь спектр транспортных услуг</p>

    </div>
</div>
<div class="row mb-2">
    <div class="col-md-12">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">

                <h3 class="mb-0">
                    {% if user.is_authenticated %}

                    <div class=class="btn-group">
                        <h4>Быстрые ссылки</h4>
                        <a class="btn btn-outline-secondary" href="{% url 'logistics:itineraries_plan_list' %}">
                            Запланированные разгрузки</a>

                    </div>
                    {% else %}
                    <a href="{% url 'users:login' %}">Чтобы продолжить, необходимо авторизоваться</a>
                    {% endif %}
                </h3>
                <br>

                <div class="mb-1 text-muted"></div>
                <p class="card-text mb-auto"></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

logistics/templates/logistics/itineraries_list.html
{% extends 'logistics/base.html' %}

{% block content%}

<title>{{ title }}</title>

<div class="container">

    <div class="row">
        <div class="col-12">
            <h3>Список маршрутов</h3>
            <table class="table table-condensed table-bordered table-striped">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Дата</th>
                    <th>Дата разгрузки</th>
                    <th>Место разгрузки</th>
                    <th>Транспортное средство</th>
                    <th>Водитель</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                {% for itinerary in itineraries %}
                <tr>
                    <td>{{ itinerary.itinerary_number }}</td>
                    <td>{{ itinerary.itinerary_date.date }}</td>
                    <td>{{ itinerary.itinerary_date_finish }}</td>
                    <td>{{ itinerary.itinerary_point_to }}</td>
                    <td>{{ itinerary.itinerary_vehicle }}</td>
                    <td>{{ itinerary.itinerary_driver }}</td>
                    <td>
                        <a href="{% url 'logistics:itinerary_update' itinerary.pk %}"
                           class="btn btn-condensed btn-sm btn-outline-warning">Редактировать</a>
                        <a href="{% url 'logistics:itinerary_delete' itinerary.pk %}"
                           class="btn btn-condensed btn-sm btn-outline-danger">Удалить</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <a href="{% url 'logistics:itinerary_create' %}" class="btn btn-sm btn-outline-success">
            Добавить маршрут</a>
    </div>
</div>
<br>
<style>
    /* Стили для шрифта таблицы */
.table-condensed{
  font-size: 12px;
  line-height: 0;
}

/* Стили для шрифта кнопок в таблице */
.btn-condensed{
  font-size: 12px;
}
</style>
{% endblock %}

logistics/templates/logistics/itineraries_plan_list.html
{% extends 'logistics/base.html' %}

{% block content%}

<title>{{ title }}</title>

<div class="container">

    <div class="row">
        <div class="col-12">
            <h3>Запланированные разгрузки</h3>
            <table class="table table-condensed table-bordered">
                <thead>
                <tr class="table-secondary">
                    <th>Менеджер</th>
                    {% for day in days %}
                    <th>{{ day }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for user in users %}


                {% for itinerary in itineraries %}
                {% if itinerary.itinerary_owner == user %}

                <tr>
                    <td>{{ user.first_name }}</td>

                    {% for day in days %}
                    <td>
                        {% if itinerary.itinerary_date_finish.date == day %}
                        <a href="#">
                            {{ itinerary.itinerary_vehicle }} | {{ itinerary.itinerary_point_to }}</a>
                        {% endif %}
                    </td>
                    {% endfor %}

                </tr>
                    {% endif %}
                {% endfor %}

                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
<br>
<style>
    /* Стили для шрифта таблицы */
.table-condensed{
  font-size: 12px;
  line-height: 0;

}

</style>
{% endblock %}

logistics/templates/logistics/itinerary_confirm_delete.html
{% extends "logistics/base.html" %}

{% block content %}

    <div class="col-lg-4 col-md-8">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h4 class="card-title">Хотите удалить маршрут: </h4>
                            <p>{{itinerary.itinerary_number}} ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'logistics:itineraries_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<br>
{% endblock %}

logistics/templates/logistics/itinerary_form.html
{% extends 'logistics/base.html' %}

{% block content%}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if itinerary %}
                        <h3 class="card-title text-center">Редактирование маршрута</h3>
                        {% else %}
                        <h3 class="card-title text-center">Новый маршрут</h3>
                        {% endif %}
                        <p></p>
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <div class="col-6">
                        <div id="line_1">
                            <div id="left_1">Номер заявки</div>
                            <div id="center_1"></div>
                            <div id="right_1">
                                <div class="form-floating mb-3">
                                    <input class="form-control input-box form-ensurance-header-control"
                                           type="text"
                                           name="itinerary_number"/>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        <div id="line_2">
                            <div id="date_from">Дата погрузки</div>
                            <div id="date_1">
                                <div class="form-floating mb-3">
                                    <input class="form-control input-box form-ensurance-header-control"
                                           type="datetime-local"
                                           name="itinerary_date_start"/>
                                </div>
                            </div>
                            <div id="center_2"></div>
                            <div id="date_to">Дата разгрузки</div>
                            <div id="date_2">
                                <div class="form-floating mb-3">
                                    <input class="form-control input-box form-ensurance-header-control"
                                           type="datetime-local"
                                           name="itinerary_date_finish"/>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        <div id="line_3">
                            <div id="where_from">Место погрузки</div>
                            <div id="city_1">
                                <div class="form-floating mb-3">
                                    <input class="form-control input-box form-ensurance-header-control"
                                           type="text"
                                           name="itinerary_point_from"/>
                                </div>
                            </div>
                            <div id="center_3"></div>
                            <div id="where_to">Место разгрузки</div>
                            <div id="city_2">
                                <div class="form-floating mb-3">
                                    <input class="form-control input-box form-ensurance-header-control"
                                           type="text"
                                           name="itinerary_point_to"/>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-8">
                        <div id="line_4">
                            <div id="left_4">Транспортное средство</div>
                            <div id="center_4"></div>
                            <div id="right_4">
                                <div class="form-floating mb-3">
                                    <select name="itinerary_vehicle">
                                        {% for vehicle in vehicles %}
                                        <option value="{{ vehicle.pk }}">{{ vehicle.vehicle_registration }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-8">
                        <div id="line_5">
                            <div id="left_5">Водитель</div>
                            <div id="center_5"></div>
                            <div id="right_5">
                                <div class="form-floating mb-3">
                                    <select name="itinerary_driver">
                                        {% for driver in drivers %}
                                        <option value="{{ driver.pk }}">{{ driver.driver_name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br>
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
            </div>
        </div>

    </form>
</div>
<br>

<style>
    /* Стили для ввода номера заявки */
    #line_1 {
      display: flex;
    }

    #left_1 {
      width: 30%;
      font-size: 12px;
    }
    #center_1 {
      width: 10%;
    }

    #right_1 {
      width: 50%;
    }

    /* Стили для ввода дат погрузки и разгрузки */
    #line_2 {
      display: flex;
    }

    #date_from {
      width: 10%;
      font-size: 12px;
    }
    #date_1 {
      width: 25%;
    }
    #center_2 {
      width: 10%;
    }
    #date_to {
      width: 10%;
      font-size: 12px;
    }
    #date_2 {
      width: 25%;
    }

    /* Стили для ввода мест погрузки и разгрузки */
    #line_3 {
      display: flex;
    }

    #where_from {
      width: 10%;
      font-size: 12px;
    }
    #city_1 {
      width: 25%;
    }
    #center_3 {
      width: 10%;
    }
    #where_to {
      width: 10%;
      font-size: 12px;
    }
    #city_2 {
      width: 25%;
    }

    /* Стили для ввода авто */
    #line_4 {
      display: flex;
    }

    #left_4 {
      width: 20%;
      font-size: 12px;
    }
    #center_4 {
      width: 10%;
    }

    #right_4 {
      width: 50%;
      font-size: 12px;
    }

    /* Стили для ввода водителя */
    #line_5 {
      display: flex;
    }

    #left_5 {
      width: 20%;
      font-size: 12px;
    }
    #center_5 {
      width: 10%;
    }

    #right_5 {
      width: 50%;
      font-size: 12px;
    }

</style>
{% endblock %}